import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import { Inter } from "next/font/google";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className="flex flex-col-reverse md:flex-row">
            <Navbar />
            <section className="w-full flex justify-center bg-gray-200">
              <section className="w-10/12 mt-10">
                {children}
              </section>
            </section>
        </body>
    </html>
  );
}
